PlayMap/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="array")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="boolean")
     */
    private $newsletter;

    /**
     * @ORM\Column(type="integer")
     */
    private $grade;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\OneToOne(targetEntity=Stat::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $stat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birthday;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }

    public function getGrade(): ?int
    {
        return $this->grade;
    }

    // RPR ** niveau de l'utilisateur
    public function getGradeLabel(): ?string
    {
        $tab = ['Débutant déjà pro', 'Challengeur', 'Presque intouchable', 'Winner dans l\'âme', 'Grand Pro', 'Étoile née', 'Big Boss'];
        $niveau = $tab[$this->grade];
        return $niveau;
    }

    // RPR ** niveau de la progression
    public function getGradeProg(): ?string
    {
        $tab = ['15%', '28%', '39%', '47%', '65%', '81%', '100%'];
        $niveau = $tab[$this->grade];
        return $niveau;
    }

    public function setGrade(int $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getStat(): ?Stat
    {
        return $this->stat;
    }

    public function setStat(Stat $stat): self
    {
        // set the owning side of the relation if necessary
        if ($stat->getUser() !== $this) {
            $stat->setUser($this);
        }

        $this->stat = $stat;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }
}

PlayMap/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Beta;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{


  public function index(): Response
  {
    return $this->render('home/home.html.twig');
  }





  public function beta(): Response
  {
    // return $this->render('home/index.html.twig', [
    //     'controller_name' => 'HomeController',
    // ]);

    $em = $this->getDoctrine()->getManager();

    $betas = $em->getRepository(Beta::class)->findAll();

    return $this->render('home/beta.html.twig', [
      'betas' => $betas
    ]);
  }


  public function inscription(): Response
  {
    // return $this->render('home/index.html.twig', [
    //     'controller_name' => 'HomeController',
    // ]);

    return $this->render('inscription/inscription.html.twig');
  }


  // fonction de récupération données API
  public function getDatabase()
  {

    $em = $this->getDoctrine()->getManager();
    $allBetas = $em->getRepository(Beta::class)->findAll();

    $arrayCollection = array();

    foreach ($allBetas as $item) {
      $arrayCollection[] = array(
        'id' => $item->getId(),
        'name' => $item->getName(),
        'age' => $item->getAge()
      );
    }

    return new JsonResponse($arrayCollection);
  }
}

PlayMap/templates/home/beta.html.twig
{% extends 'layout.html.twig' %}


{% block title %}
	{{ parent() }}
	- beta
{% endblock %}


{% block content %}
	{{ parent() }}

	<div class="container">
		<div class="row my-5">
			<div class="col">

        {% if app.user %}
          <p class="text-danger">Ce message apparaît si un utilisateur est connecté : user = {{ app.user.pseudo }}</p>
        {% endif %}

				<h2>Page de test</h2>
				<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos magni praesentium nam voluptatem corrupti natus. Maxime debitis quo, quidem, voluptates molestias asperiores et vero delectus dolor distinctio, corporis voluptatem aut.</p>
			</h2>
      <div id="react-root" class="my-3"></div>


			<table class="table">
				<thead class="thead-dark">
					<tr>
						<th>id</th>
						<th>name</th>
						<th>age</th>
					</tr>

				</thead>
				<tbody>
					{% for beta in betas %}
						<tr>
							<td>{{beta.id}}</td>
							<td>{{beta.name}}</td>
							<td>{{beta.age}}</td>
						</tr>
					{% endfor %}

				</tbody>
			</table>

		</div>
	</div>
  <div class="row">
    <div class="col">
      <div id="react-root"></div>
    </div>
  </div>
</div>{% endblock %}

PlayMap/templates/home/home.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
	{{ parent() }}- Home
{% endblock %}

{% block content %}

	<main>

		<!-- MODALE UTILISATEUR -->
		<div id="user-acc" class="d-none" style="opacity: 0;">

			<section class="user-avatar text-center">
				<img class="w-25" src="{{ asset('images/old-man.png') }}" alt="">
			</section>

			<section class="user-pseudo my-2">
				<div>
					{% if app.user %}
						<p>{{ app.user.pseudo }}</p>
					{% endif %}
				</div>
			</section>

			<section class="user-grade my-3">
				<p>
          {% if app.user %}
						— {{ app.user.gradeLabel }} —
					{% endif %}
        </p>
			</section>

			<!-- A*A -- PROGRESSION -->
			<section class="user-level d-flex justify-content-center align-items-center my-3">

				<div class="user-level-logo">
					<img src="images/BadgeOr.png" alt="">
				</div>

				<div class="user-level-prog">
          <div></div>
          <div class="user-level-prog-int bg-warning"></div>
        </div>

				<div class="user-level-logo">
					<img src="images/Médaille.png" alt="">
				</div>

			</section>

			<!-- A*A -- STATS -->
			<section class="user-stats d-flex justify-content-between">

				<div class="user-stats-icon">
					<p>85<br>km</p>
				</div>
				<div class="user-stats-icon">
					<p>2000<br>calories</p>
				</div>
				<div class="user-stats-icon">
					<p>250 g<br>Co2/km</p>
				</div>

			</section>

			<section class="user-account my-3 text-center">
				{% if app.user %}
					<a class="btn btn-account" href="{{ path('account', {('id'): app.user.id}) }}">Voir profil</a>
				{% endif %}
			</section>


		</div>
		<!-- FIN DU MODALE UTILISATEUR -->


		<!--MAIN-->

		<div class="container">

			<div
				class="row">

				<!-- RPR -- BLOC DE GAUCHE ****************************************************** -->
				<div class="col-4 text-center justify-content-center">
					<div class="cadreChallenge ">
						<h3>Mes Challenges</h3>
						<div class="cadreChallenge2">
							<p>Pas de Challenge en cours...</p><br>
							<a href="" class="">Inscrivez-vous pour participer aux challenges !</a>
						</div>
					</div>
				</div>


				<!-- RPR -- BLOC DU CENTRE ****************************************************** -->
				<div class="col-4">

					<div class="row justify-content-center ombreTransport">
						<img class="ombreVelo" src="{{ asset('images/Ombre+Vélo.png') }}">
						<img class="ombretrottinette d-none" src="{{ asset('images/ombretrottinette.png') }}">
						<img class="ombrePied d-none" src="{{ asset('images/Icon_Apied.png') }}">
						<p class="selection med-txt">Sélectionnez votre moyen de transport :</p>
					</div>

					<div class="row justify-content-center">

						<div class="btnTransport">
							<button type="button" id="btnVelo" class="btn text-light med-txt">Vélo</button>
						</div>
						<div class="btnTransport">
							<button type="button" id="btnTrottinette" class="btn text-light med-txt">Trottinette</button>
						</div>
						<div class="btnTransport">
							<button type="button" id="btnPied" class="btn text-light med-txt">A Pieds</button>
						</div>

						<!-- FIN MOYEN DE TRANSPORTS-->

					</div>


					<!--A*A-- FORMULAIRE ITINERAIRE -->
					<form>
						<div class="form-group" style="">
							<label for="start">Départ</label>
							<input type="text" class="form-control" id="start" placeholder="Adresse de départ" name="start">
						</div>

						<div class="Vector">
							<img class="float-right" src="{{ asset('images/vector.png') }}" alt="VECTOR">
						</div>

						<div class="form-group">
							<label for="stop">Arrivée</label>
							<input type="text" class="form-control" id="stop" placeholder="Adresse d'arrivée" name="stop">
						</div>

						<div class="row justify-content-around">
							<button type="button" id="search" class="btn btn-warning text-light mb-4" name="search">Allons-y !</button>
							<button type="button" id="btnGo" class="btn btn-danger text-light mb-4">Valider mon Trajet !</button>
						</div>


					</form>
					<!--FIN INPUT DEPART ARRIVEE-->

				</div>

				<!-- RPR -- BLOC DE DROITE ****************************************************** -->
				<div
					class="col-4">
					<!--METEO ****************************************************** -->

					<div class="meteo">
						<div
							class="row">
							<!-- row météo -->

							<div class="col-6 p-3 mb-2 text-white">
								<p id="cityTemp" class="font-weight-bold"></p>
							</div>

							<div class="col-6">
								<div>
									<img id="temp" src="" alt="">
								</div>
							</div>

						</div>
					</div>

					<div
						class="row">
						<!-- row trajet -->

						<div class="col p-3 mt-5 mb-3 statsTrajet">

							<div class="statsTrajetHaut">
								<p>12 km</p>
								<p>25 min</p>
							</div>
							<div class="statsTrajetBas d-flex justify-content-between">
								<article>
									<p>2000
										<br>calories</p>
								</article>
								<article>
									<p>1056
										<br>co2</p>
								</article>
								<article>
									<img id="transport" src="{{ asset('images/Vélo.png') }}" alt="transport mobilité">
								</article>
							</div>

						</div>

					</div>

					<div
						class="row">
						<!-- row favoris -->
						<button class="btn btn-warning text-light mx-auto">Enregistrer dans les favoris</button>
					</div>

				</div>

			</div>

		</div>
		<!-- fin du container -->


		<!--MAP-->
		<div class="container-fluid">
			<div id="carte" class="map"></div>
		</div>
		<!-- FIN MAP-->


		<!-- MODALE CHALLENGER -->

		<div id="user-chal" class="d-none p-4 ">
			<section class="border-chal text-center py-3">

				<section class="badge">
					<img src="{{ asset('images/badge.png') }}" alt="BADGE">
					<h4 class="font-weight-bold">Bien Joué !
						<br>
						Vous êtes arrivé !</h4>
				</section>

				<section class="cumuler font-weight-bold">
					<p class="text-light">
						Vous Avez Cumulé :
					</p>
					<p class="text-warning">
						+ 3 Km
					</p>
					<p class="text-danger">
						- 200 Calories
					</p>
					<p class="text-info">
						- 20g co2/km
					</p>
				</section>
			</section>

		</div>

		<!-- FIN DU MODALE CHALLENGER -->

	</main>


{% endblock %}